name: Deplot de la pagina
on: 
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-lates
    steps:
     - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
