name: Deplot de la pagina
on: 
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.1.4
        with:
          branch: gh-pages
          folder: . # The folder the action should deploy.
